//popup extension from http://raphaeljs.com/   +google chrome fix
(function(){var p=/\{([^\}]+)\}/g,q=/(?:(?:^|\.)(.+?)(?=\[|\.|$|\()|\[('|")(.+?)\2\])(\(\))?/g,r=function(g,h){return String(g).replace(p,function(g,e){var c=h;e.replace(q,function(d,b,f,e,a){b=b||e;c&&(b in c&&(c=c[b]),"function"==typeof c&&a&&(c=c()))});return c=(null==c||c==h?g:c)+""})};Raphael.fn.popup=function(g,h,n,e,c){e=String(e||"top-middle").split("-");e[1]=e[1]||"middle";var d=n.getBBox(),b=-1<navigator.userAgent.toLowerCase().indexOf("chrome")?Math.round(d.width)+4:Math.round(d.width),
f=Math.round(d.height),i=Math.round(d.x)-5,d=Math.round(d.y)-5,a=Math.min(f/2,b/2,10),l=[{x:i+5,y:d,w:b,w4:b/4,h4:f/4,right:0,left:b-2*a,bottom:0,top:f-2*a,r:5,h:f,gap:a},{x:i+5,y:d,w:b,w4:b/4,h4:f/4,left:b/2-a,right:b/2-a,top:f/2-a,bottom:f/2-a,r:5,h:f,gap:a},{x:i+5,y:d,w:b,w4:b/4,h4:f/4,left:0,right:b-2*a,top:0,bottom:f-2*a,r:5,h:f,gap:a}]["middle"==e[1]?1:2*("top"==e[1]||"left"==e[1])],j=0,k=0,m=this.path(r({top:"M{x},{y}h{w4},{w4},{w4},{w4}a{r},{r},0,0,1,{r},{r}v{h4},{h4},{h4},{h4}a{r},{r},0,0,1,-{r},{r}l-{right},0-{gap},{gap}-{gap}-{gap}-{left},0a{r},{r},0,0,1-{r}-{r}v-{h4}-{h4}-{h4}-{h4}a{r},{r},0,0,1,{r}-{r}z",
bottom:"M{x},{y}l{left},0,{gap}-{gap},{gap},{gap},{right},0a{r},{r},0,0,1,{r},{r}v{h4},{h4},{h4},{h4}a{r},{r},0,0,1,-{r},{r}h-{w4}-{w4}-{w4}-{w4}a{r},{r},0,0,1-{r}-{r}v-{h4}-{h4}-{h4}-{h4}a{r},{r},0,0,1,{r}-{r}z",right:"M{x},{y}h{w4},{w4},{w4},{w4}a{r},{r},0,0,1,{r},{r}v{h4},{h4},{h4},{h4}a{r},{r},0,0,1,-{r},{r}h-{w4}-{w4}-{w4}-{w4}a{r},{r},0,0,1-{r}-{r}l0-{bottom}-{gap}-{gap},{gap}-{gap},0-{top}a{r},{r},0,0,1,{r}-{r}z",left:"M{x},{y}h{w4},{w4},{w4},{w4}a{r},{r},0,0,1,{r},{r}l0,{top},{gap},{gap}-{gap},{gap},0,{bottom}a{r},{r},0,0,1,-{r},{r}h-{w4}-{w4}-{w4}-{w4}a{r},{r},0,0,1-{r}-{r}v-{h4}-{h4}-{h4}-{h4}a{r},{r},0,0,1,{r}-{r}z"}[e[0]],
l)).insertBefore(n);switch(e[0]){case "top":j=g-(i+5+l.left+a);k=h-(d+5+f+5+a);break;case "bottom":j=g-(i+5+l.left+a);k=h-(d-a);break;case "left":j=g-(i+5+b+5+a);k=h-(d+5+l.top+a);break;case "right":j=g-(i-a),k=h-(d+5+l.top+a)}m.translate(j,k);if(c)return c=m.attr("path"),m.remove(),{path:c,dx:j,dy:k};n.translate(j,k);return m}})();

//linechart v0.1 (13.12.2021)
function lineChart(q,p,t,u,v,w,y){function s(c,a){var d={},e;for(e in c)c.hasOwnProperty(e)&&(d[e]=c[e]);for(var b in a)a.hasOwnProperty(b)&&(d.hasOwnProperty(b)?"object"===typeof d[b]&&(d[b].constructor===Object&&"object"===typeof a[b]&&a[b].constructor===Object)&&(d[b]=s(d[b],a[b])):d[b]=a[b]);return d}function x(c){if(null==c||"object"!=typeof c)return c;var a=new c.constructor,d;for(d in c)a[d]=x(c[d]);return a}this.opts=s(y,{padding:[0,0,0,0],legend:{show:!1,textAttr:{font:'12px "Trebuchet MS"',
fill:"#4c4c4c",color:"#4c4c4c","text-anchor":"start"},x:0,y:0,anchor:"middle"},yAxis:{showLabels:!0,showGridLines:!0,gridLinesAttr:{stroke:"#c0c0c0","stroke-width":1,fill:"none"},gridStep:1,gridShift:0,labelsStep:1,labelsShift:0,labelsTickSize:3,isInteger:!1,pLabelsNN:5,labelsMR:5,labelsAttr:{font:'12px "Trebuchet MS"',fill:"#4c4c4c",color:"#4c4c4c","text-anchor":"start"},labelFormatter:function(c){return c}},xAxis:{showLabels:!0,showGridLines:!0,gridLinesAttr:{stroke:"#c0c0c0","stroke-width":1,fill:"none"},
gridStep:1,gridShift:0,labelsStep:1,labelsShift:0,labelsMT:4,vAlign:"bottom",labelsTickSize:3,labelsAttr:{font:'12px "Trebuchet MS"',fill:"#4c4c4c",color:"#4c4c4c","text-anchor":"middle"},labelsAngle:-45,labelFormatter:function(c){return c}}});this.r=Raphael(q,u+p,v+t);this.x=p;this.y=t;this.width=u;this.height=v;this.xValues=w;"object"==typeof this.opts.graph&&!(this.opts.graph instanceof Array)&&(this.opts.graph=[this.opts.graph]);this.graphDefault={name:"",yValues:[],showDots:!0,showLine:!0,showArea:!0,
smooth:!1,lineAttr:{stroke:"auto","stroke-width":3,"stroke-linejoin":"round"},dotAttr:{fill:"#fff",stroke:"auto","stroke-width":2},dotRadius:4,areaAttr:{stroke:"none",opacity:0.3,fill:"auto"},tooltip:{show:!0,activator:"area",dotActivatorRadius:25,tooltipAttr:{fill:"#000",stroke:"#666","stroke-width":2,"fill-opacity":0.7},labels:function(c,a,d){return c.text(10,10,d).attr({font:'13px "Trebuchet MS"',fill:"white",color:"white","text-anchor":"middle"})}}};this.dots=[];this.bgp=this.r.set();this.path=
this.r.set();this.blanket=[];this.tooltip=[];this.legend=this.r.set();if(!this.opts.colors){this.opts.colors=[];q=[0.6,0.2,0.05,0.1333,0.75,0];for(p=0;10>p;p++)p<q.length?this.opts.colors.push("hsb("+q[p]+",.75, .75)"):this.opts.colors.push("hsb("+q[p-q.length]+", 1, .5)")}-1<navigator.userAgent.toLowerCase().indexOf("firefox")&&(this.opts.yAxis.labelsMR-=5);this.drawLine=function(c,a,d,e){return this.r.path("M"+(c+0.5)+" "+(a+0.5)+"L"+(d+0.5)+" "+(e+0.5))};this.getAnchors=function(c,a,d,e,b,f){var g=
(d-c)/2,j=(b-d)/2,c=Math.atan((d-c)/Math.abs(e-a)),b=Math.atan((b-d)/Math.abs(e-f)),c=a<e?Math.PI-c:c,b=f<e?Math.PI-b:b,f=Math.PI/2-(c+b)%(2*Math.PI)/2,a=g*Math.sin(f+c),g=g*Math.cos(f+c),c=j*Math.sin(f+b),j=j*Math.cos(f+b);return{x1:d-a,y1:e+g,x2:d+c,y2:e+j}};this.calculateYLabels=function(c,a,d,e){c===a&&(c=0);for(var b=a-c,f=0;10>Math.abs(b);)b*=10,f++;b=(Math.ceil(b)+"").length-2-f;this.opts.yAxis.isInteger&&0>b&&(b=0);f=[[1*Math.pow(10,b)],[2*Math.pow(10,b)],[5*Math.pow(10,b)],[10*Math.pow(10,
b)],[20*Math.pow(10,b)],[50*Math.pow(10,b)]];i=0;for(ii=f.length;i<ii;i++)f[i].push((Math.ceil(a/f[i])*f[i]-Math.floor(c/f[i])*f[i])/f[i]+1);!0!==e&&f.reverse();f.sort(function(a,b){return Math.abs(a[1]-d)<Math.abs(b[1]-d)||a[1]-d===b[1]-d&&a[0]<b[0]?-1:Math.abs(a[1]-d)>Math.abs(b[1]-d)||a[1]-d===b[1]-d&&a[0]>b[0]?1:0});a=[];for(i=0;i<f[0][1];i++)a.push(Math.floor(c/f[0][0])*f[0][0]+i*f[0][0]),a[i]=Math.round(a[i]/Math.pow(10,b))*Math.pow(10,b);return a};this.getColor=function(){this.getColor.n=this.getColor.n||
0;return this.opts.colors[this.getColor.n++%this.opts.colors.length]};this.getColorReset=function(){this.getColor.n=0};this.showLegend=function(){this.getColorReset();i=0;for(ii=this.opts.graph.length;i<ii;i++){var c=this.getColor(i),a=0<i?this.legend.getBBox().width+20:0;this.legend.push(this.r.rect(a+0,0,30,2).attr({stroke:c,fill:c}));this.legend.push(this.r.text(a+35,0,this.opts.graph[i].name).attr(this.opts.legend.textAttr))}"start"===this.opts.legend.anchor?this.legend.transform("t"+this.opts.legend.x+
","+this.opts.legend.y):"middle"===this.opts.legend.anchor&&this.legend.transform("t"+(this.opts.legend.x-this.legend.getBBox().width/2)+","+this.opts.legend.y)};this.drawGraph=function(c,a,d,e,b){var f=this.getColor();"auto"===b.dotAttr.stroke&&(b.dotAttr.stroke=f);"auto"===b.lineAttr.stroke&&(b.lineAttr.stroke=f);"auto"===b.areaAttr.fill&&(b.areaAttr.fill=f);"auto"===b.tooltip.tooltipAttr.stroke&&(b.tooltip.tooltipAttr.stroke=f);f=(c.x2-c.x1)/(a.length-1);e=(c.y2-c.y1)/(e-d);this.dots.push(this.r.set());
var g=this.dots[this.dots.length-1],j,m;this.tooltip.push([]);var n=this.tooltip[this.tooltip.length-1];this.blanket.push(this.r.set());for(var p=this.blanket[this.blanket.length-1],k=0,q=this.xValues.length;k<q;k++){var l=Math.round(f*k)+c.x1,h=c.y2-Math.round(e*(b.yValues[k]-d));g.push(this.r.circle(l,h,b.dotRadius).attr(b.dotAttr));if(!0===b.smooth){if(k||(j=["M",l,h,"C",l,h],m=["M",c.x1,c.y2,"L",l,h,"C",l,h]),k&&k<q-1){var r=c.y2-Math.round(e*(b.yValues[k-1]-b.yValues[0])),s=Math.round(f*(k-1))+
c.x1,t=c.y2-Math.round(e*(b.yValues[k+1]-b.yValues[0])),u=Math.round(f*(k+1))+c.x1,r=this.getAnchors(s,r,l,h,u,t);j=j.concat([r.x1,r.y1,l,h,r.x2,r.y2]);m=m.concat([r.x1,r.y1,l,h,r.x2,r.y2]);j.concat([l,h])}}else k||(j=["M",l,h,"L",l,h],m=["M",c.x1,c.y2,"L",l,h]),k&&k<q-1&&(j=j.concat([l,h]),m=m.concat([l,h]));"area"===b.tooltip.activator?p.push(this.r.rect(0===k?c.x1:c.x1+f*(k-0.5),c.y1,0===k||k===q-1?0.5*f:f,c.y2-c.y1).attr({stroke:"none",fill:"#fff",opacity:0})):"dot"===b.tooltip.activator&&p.push(this.r.circle(l,
h,b.tooltip.dotActivatorRadius).attr({fill:"#fff",stroke:"none",opacity:0}));var v=p[p.length-1];!0===b.tooltip.show&&function(d,f,e,j,l){v.hover(function(){if(!n[e]){n[e]=[j.set(),j.set()];var h=b.tooltip.labels(j,a[e],b.yValues[e],e);"object"==typeof h&&h instanceof Array||(h=[h]);h.reverse();for(var k=0,m=h.length;k<m;k++)n[e][0].push(h[k].hide().insertBefore(l[0]));n[e][1]=j.popup(d,f,n[e][0],"right").attr(b.tooltip.tooltipAttr).hide().insertBefore(n[e][0]);d+n[e][1].getBBox().width>c.x2&&(n[e][1].remove(),
n[e][1]=j.popup(d,f,n[e][0],"left").attr(b.tooltip.tooltipAttr).hide().insertBefore(n[e][0]))}n[e][0].show();n[e][1].show();g[e].attr("r",b.dotRadius+2)},function(){n[e][0].hide();n[e][1].hide();g[e].attr("r",b.dotRadius)})}(l,h,k,this.r,this.blanket)}j=j.concat([l,h,l,h]);m=m.concat([l,h,l,h,"L",l,c.y2,"z"]);this.path.push(this.r.path().attr(b.lineAttr).attr({path:j}));this.bgp.push(this.r.path().attr(b.areaAttr).attr({path:m}));!0!==b.showLine&&this.path[this.path.length-1].hide();!0!==b.showArea&&
this.bgp[this.bgp.length-1].hide();!0!==b.showDots&&g.hide()};this.draw=function(){!0===this.opts.legend.show&&this.showLegend();for(var c=[],a=0,d=this.opts.graph.length;a<d;a++)c=c.concat(this.opts.graph[a].yValues);for(var a=Math.max.apply(Math,c),d=Math.min.apply(Math,c),e=this.r.set(),c=this.r.set(),b=this.calculateYLabels(d,a,this.opts.yAxis.pLabelsNN||this.opts.d.yAxis.pLabelsNN),f=[0,0],a=0,d=b.length;a<d;a++)e.push(this.r.text(0,0,this.opts.yAxis.labelFormatter(b[a],a)).attr(this.opts.yAxis.labelsAttr).hide()),
e[a].getBBox().width+this.opts.yAxis.labelsMR>f[0]&&(f[0]=e[a].getBBox().width+this.opts.yAxis.labelsMR);a=0;for(d=this.xValues.length;a<d;a++)c.push(this.r.text(0,0,this.opts.xAxis.labelFormatter(this.xValues[a],a)).attr(this.opts.xAxis.labelsAttr).rotate(this.opts.xAxis.labelsAngle).hide()),c[a].getBBox().height+this.opts.xAxis.labelsMT>f[1]&&(f[1]=c[a].getBBox().height+this.opts.xAxis.labelsMT);for(var g={x1:Math.round(this.x+(!0===this.opts.yAxis.showLabels?f[0]:0)+this.opts.padding[3]),y1:Math.round(this.y+
e[e.length-1].getBBox().height/2+this.opts.padding[0]),x2:Math.round(this.x+this.width-c[c.length-1].getBBox().width/2-this.opts.padding[1]),y2:Math.round(this.y+this.height-(!0===this.opts.xAxis.showLabels?f[1]:0)-this.opts.padding[2])},j=(g.x2-g.x1)/(w.length-1),m=(g.y2-g.y1)/(b[b.length-1]-b[0]),a=0,d=b.length;a<d;a++)0<=a-this.opts.yAxis.gridShift&&(!((a-this.opts.yAxis.gridShift)%this.opts.yAxis.gridStep)&&!0===this.opts.yAxis.showGridLines)&&this.drawLine(g.x1,g.y2-Math.round((b[a]-b[0])*m),
this.x+this.width-this.opts.padding[1],g.y2-Math.round((b[a]-b[0])*m)).attr(this.opts.yAxis.gridLinesAttr).toBack(),0<=a-this.opts.yAxis.labelsShift&&(!((a-this.opts.yAxis.labelsShift)%this.opts.yAxis.labelsStep)&&!0===this.opts.yAxis.showLabels)&&(e[a].attr({x:this.x+this.opts.padding[3],y:g.y2-Math.round((b[a]-b[0])*m)}).show(),this.drawLine(g.x1-this.opts.yAxis.labelsTickSize,g.y2-Math.round((b[a]-b[0])*m),g.x1,g.y2-Math.round((b[a]-b[0])*m)).attr(this.opts.yAxis.gridLinesAttr).toBack());a=0;for(d=
this.xValues.length;a<d;a++)0<=a-this.opts.xAxis.gridShift&&(!((a-this.opts.xAxis.gridShift)%this.opts.xAxis.gridStep)&&!0===this.opts.xAxis.showGridLines)&&this.drawLine(g.x1+Math.round(a*j),this.y+this.opts.padding[0],g.x1+Math.round(a*j),g.y2).attr(this.opts.xAxis.gridLinesAttr).toBack(),0<=a-this.opts.xAxis.labelsShift&&(!((a-this.opts.xAxis.labelsShift)%this.opts.xAxis.labelsStep)&&!0===this.opts.xAxis.showLabels)&&(e=Math.round(g.y2+f[1]-c[a].getBBox().height/2),"top"==this.opts.xAxis.vAlign&&
(e=Math.round(g.y2+this.opts.xAxis.labelsMT+c[a].getBBox().height/2)),c[a].rotate(-this.opts.xAxis.labelsAngle).attr({x:g.x1+Math.round(a*j),y:e}).rotate(this.opts.xAxis.labelsAngle).show(),this.drawLine(g.x1+Math.round(a*j),g.y2,g.x1+Math.round(a*j),g.y2+this.opts.xAxis.labelsTickSize).attr(this.opts.xAxis.gridLinesAttr).toBack());this.getColorReset();a=0;for(d=this.opts.graph.length;a<d;a++)c=x(s(this.opts.graph[a],this.graphDefault)),this.drawGraph(g,this.xValues,b[0],b[b.length-1],c);this.bgp.toFront();
this.path.toFront();a=0;for(d=this.dots.length;a<d;a++)this.dots[a].toFront();a=0;for(d=this.blanket.length;a<d;a++)this.blanket[a].toFront()};this.addText=function(c,a,d,e){this.r.text(c,a,d).attr(e)}};